Repository github/backup-utils, pull requests merged in 2018-03, with the labels that each got.

#374 Use primary index size to determine if an index has changed
  share/github-backup-utils/ghe-backup-es-audit-log
  share/github-backup-utils/ghe-backup-es-hookshot
  test/bin/curl
Labels: cluster

#378 Move check for git for ssh muxing into ghe-ssh
  bin/ghe-backup
  share/github-backup-utils/ghe-ssh
Labels: bug

#384 Output backup utils version on backup and restore
  bin/ghe-backup
  bin/ghe-restore
Labels: enhancement
